# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://wildcloud3.github.io/nbdev/"

git_url = "https://github.com/wildcloud3/nbdev/tree/master/"

def custom_doc_links(name): return None
